### ISSUE TITLE
`fedify inbox` throws a `ShikiError` during rendering web interface

### ISSUE THREAD

**Issue by dahlia** [dahlia/fedify#178]
The `fedify inbox` commands throws an exception during rendering web interface:

```
ShikiError: Theme `github-light` not found, you may need to load it first
    at getTheme (file:///Users/dahlia/Library/Caches/deno/npm/registry.npmjs.org/@shikijs/core/1.6.4/dist/index.mjs:5378:19)
    at Object.setTheme (file:///Users/dahlia/Library/Caches/deno/npm/registry.npmjs.org/@shikijs/core/1.6.4/dist/index.mjs:5382:23)
    at codeToTokensBase (file:///Users/dahlia/Library/Caches/deno/npm/registry.npmjs.org/@shikijs/core/1.6.4/dist/index.mjs:527:42)
    at codeToTokens (file:///Users/dahlia/Library/Caches/deno/npm/registry.npmjs.org/@shikijs/core/1.6.4/dist/index.mjs:784:18)
    at codeToHast (file:///Users/dahlia/Library/Caches/deno/npm/registry.npmjs.org/@shikijs/core/1.6.4/dist/index.mjs:1016:53)
    at codeToHtml (file:///Users/dahlia/Library/Caches/deno/npm/registry.npmjs.org/@shikijs/core/1.6.4/dist/index.mjs:4602:25)
    at Object.codeToHtml (file:///Users/dahlia/Library/Caches/deno/npm/registry.npmjs.org/@shikijs/core/1.6.4/dist/index.mjs:5431:40)
    at CodeBlock (file:///Users/dahlia/Projects/fedify/cli/inbox/view.tsx:117:30)
    at JSXFunctionNode.toStringToBuffer (https://jsr.io/@hono/hono/4.6.3/src/jsx/base.ts:245:40)
    at childrenToStringToBuffer (https://jsr.io/@hono/hono/4.6.3/src/jsx/base.ts:102:13) {
  name: "ShikiError"
}
```

**Comment by Heesunni** [comment]
해볼께요!
